CREATE DATABASE db_supremo_crm;

CREATE TABLE contacts (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    cpf VARCHAR(14) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

